function updateUI(){
 $("time").textContent=`${Math.floor(S.stageTime)}s`;
 $("score").textContent=S.score.toLocaleString();
 $("combo").textContent="x"+S.combo.toFixed(1);
 $("phase").textContent=`STAGE ${S.stage}${S.stage>=5?" ★":""} · ${phaseName()}`;
 $("pipLevel").innerHTML=pipWithPlayer()?`<b>PIP LV ${S.pipLevel}</b> · ${S.pipXP}/${pipNeed(S.pipLevel)} XP · ♥R ${Math.round(S.pipDetectRange)}px · ✦P ${S.pipPowerLv} · ◇G ${S.pipGuardLv} · ✧B ${Object.keys(S.pipBossPowers||{}).length}`:`<b>PIP AWAY</b> · BONUSES OFF · ♥ hunting`;
 $("currencyHud").textContent=`♥ ${S.heartCurrency} WALLET · ${S.heartTotal||0} TOTAL`;
 if(S.audioEnabled)$("audioToggle").textContent=(audioCtx&&audioCtx.state==="running")?"♫ ON":"♫ TAP";
 $("dashBar").style.width=(S.over>0?100:(1-clamp(S.dashCd/S.dashMax,0,1))*100)+"%";$("heatBar").style.width=clamp(S.heat,0,100)+"%";$("attack").textContent=S.over>0?"AUTO x3":"AUTO";
 $("dash").classList.toggle("ready",S.dashCd<=0||S.over>0);$("dash").classList.toggle("over",S.over>0);$("dash").textContent=S.over>0?"GO!":S.dashCd<=0?"DASH":"...";
 $("healthBar").style.width=(S.health/S.maxHealth*100)+"%";$("shieldPips").innerHTML=Array.from({length:S.maxShields},(_,i)=>`<i class="shieldpip ${i<S.shields?"":"empty"}"></i>`).join("");
 if(S.shields>=S.maxShields){$("regenText").textContent="FULL"}else if(S.shieldRegenClock<0){$("regenText").textContent="WAIT "+Math.ceil(-S.shieldRegenClock)+"s"}else{$("regenText").textContent="REGEN "+Math.max(0,S.shieldRegenRate-S.shieldRegenClock).toFixed(1)}
 const tgt=getAutoTarget();
 $("tip").textContent=S.bossActive?`${S.bossName} · ${Math.max(0,Math.round((enemies.find(e=>e.type==="boss")?.hp||0)))} HP`:S.waveState==="break"?`${S.stageEnding?"STAGE CLEAR":"REST"} ${Math.max(0,S.waveBreak).toFixed(1)}s`:!pipWithPlayer()?`PIP COLLECTING · BONUSES OFF`:tgt?`LOCK ${tgt.type.toUpperCase()} · ${S.waveKills}/${S.waveGoal} · PIP ♥ RANGE ${S.pipDetectRange}`:`STAGE ${S.stage} · ${Math.floor(S.stageTime)}s · ♥ RANGE ${S.pipDetectRange}`;
 if(S.pipHappy<=0&&S.run){const moods=S.over>0?"✦ Pip: YOU EARNED THIS ✦":S.combo>=4?"✦ Pip: you're incredible":S.shields===0?"✦ Pip: I believe in you completely":S.health<50?"✦ Pip: stay with me, superstar":S.pipLevel>=5?"✦ Pip: being your partner is my favorite thing":S.pipLevel>=3?"✦ Pip: I'm so glad we're a team":"✦ Pip: you're doing amazing";$("pipMood").textContent=moods}
}
function finish(dead){
 if(S.end)return;S.end=true;S.run=false;let grade=S.score>=25000?"S":S.score>=16000?"A":S.score>=9000?"B":S.score>=4500?"C":"D";$("grade").textContent=grade;$("endTitle").textContent=dead?"Arena got you.":"Run complete.";
 $("endStats").innerHTML=[["Score",S.score.toLocaleString()],["Stage",S.stage],["Pip","Lv "+S.pipLevel],["Health",Math.ceil(S.health)]].map(x=>`<div class="mini"><span class="small">${x[0]}</span><b>${x[1]}</b></div>`).join("");
 const [playTitle,playLine]=styleTitle();let line=S.bestCombo>=6?"Pip noticed your rhythm immediately and is now unbearably proud of you. ":S.chains>=4?"Pip would like the record to show that your explosions were art. ":"Pip had the best time in the world surviving stages with you. ";$("endTitle").textContent=playTitle;$("endText").textContent=line+playLine+` Pip is now level ${S.pipLevel} (${pipBondName(S.pipLevel)}). You own ${S.audioUnlocks.size}/${AUDIO_CATALOG.length} sound unlocks. Pip remembers the XP and the music you earned together.`;$("end").classList.remove("hidden");burstTone(grade==="S"?440:220,5);
}
function drawGrid(t){const grid=42,ox=(((-CAM.x+W/2)%grid)+grid)%grid,oy=(((-CAM.y+H/2)%grid)+grid)%grid;X.strokeStyle=S.over>0?"#4f391324":"#18305235";X.lineWidth=1;X.beginPath();for(let x=ox;x<W;x+=grid){X.moveTo(x,0);X.lineTo(x,H)}for(let y=oy;y<H;y+=grid){X.moveTo(0,y);X.lineTo(W,y)}X.stroke();const big=grid*5,box=(((-CAM.x+W/2)%big)+big)%big,boy=(((-CAM.y+H/2)%big)+big)%big;X.strokeStyle=S.over>0?"#8a612518":"#244a761f";X.beginPath();for(let x=box;x<W;x+=big){X.moveTo(x,0);X.lineTo(x,H)}for(let y=boy;y<H;y+=big){X.moveTo(0,y);X.lineTo(W,y)}X.stroke()}
function draw(){
 let sx=rr(-shake,shake),sy=rr(-shake,shake);X.save();X.translate(sx,sy);X.fillStyle=S.over>0?"#120d08":"#05070b";X.fillRect(-30,-30,W+60,H+60);drawGrid(S.t);
 const psx=worldToScreenX(P.x),psy=worldToScreenY(P.y);let g=X.createRadialGradient(psx,psy,40,psx,psy,Math.max(W,H)*.75);g.addColorStop(0,"#00000000");g.addColorStop(1,S.over>0?"#8a5a142c":"#0b18322f");X.fillStyle=g;X.fillRect(0,0,W,H);
 X.save();X.translate(W/2-CAM.x,H/2-CAM.y);
 for(const r of rings){if(!worldVisible(r.x,r.y,r.max+50))continue;X.globalAlpha=clamp(r.life/.35,0,1);X.strokeStyle=r.c;X.lineWidth=2;X.beginPath();X.arc(r.x,r.y,r.r,0,Math.PI*2);X.stroke()}X.globalAlpha=1;
 for(const q of particles){if(!worldVisible(q.x,q.y,80))continue;X.globalAlpha=clamp(q.life/q.max,0,1);X.fillStyle=q.c;X.beginPath();X.arc(q.x,q.y,q.r,0,Math.PI*2);X.fill()}X.globalAlpha=1;
 for(let i=0;i<P.trail.length;i++){let tr=P.trail[i],a=(i/P.trail.length)*tr.a*.45;X.globalAlpha=a;X.fillStyle=S.over>0?COLORS.gold:COLORS.player;X.beginPath();X.arc(tr.x,tr.y,4+i/P.trail.length*5,0,Math.PI*2);X.fill()}X.globalAlpha=1;
 for(const s of shots){if(!worldVisible(s.x,s.y,40))continue;X.fillStyle=S.over>0?"#ffd36f":"#d9c8ff";X.beginPath();X.arc(s.x,s.y,s.r,0,Math.PI*2);X.fill()}
 for(const h of heartBits){if(!worldVisible(h.x,h.y,40))continue;const bob=Math.sin(S.t*6+h.bob)*2;X.save();X.translate(h.x,h.y+bob);X.fillStyle="#ff9fba";X.font="bold 16px system-ui";X.textAlign="center";X.fillText("♥",0,5);X.textAlign="start";X.restore()}
 for(const w of wishes){if(!worldVisible(w.x,w.y,50))continue;const bob=Math.sin(S.t*5+w.bob)*3;X.save();X.translate(w.x,w.y+bob);X.rotate(w.spin);X.fillStyle="#ffd36f";X.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2===0?9:4,xx=Math.cos(a)*r,yy=Math.sin(a)*r;i?X.lineTo(xx,yy):X.moveTo(xx,yy)}X.closePath();X.fill();X.restore()}
 for(const s of enemyShots){if(!worldVisible(s.x,s.y,50))continue;X.fillStyle=s.c||"#ff7dd8";X.beginPath();X.arc(s.x,s.y,s.r,0,Math.PI*2);X.fill();X.globalAlpha=.25;X.beginPath();X.arc(s.x,s.y,s.r+5,0,Math.PI*2);X.fill();X.globalAlpha=1}
 const autoTarget=getAutoTarget();
 for(const e of enemies){if(e.dead||!worldVisible(e.x,e.y,220))continue;if((e.markTime||0)>0){X.strokeStyle="#ff9fba";X.lineWidth=2.4;X.beginPath();X.arc(e.x,e.y,e.r+15+Math.sin(S.t*8)*2,0,Math.PI*2);X.stroke();X.fillStyle="#ff9fba";X.font="bold 11px system-ui";X.textAlign="center";X.fillText("♥",e.x,e.y-e.r-19);X.textAlign="start"}if(autoTarget===e){X.strokeStyle=S.over>0?"#ffd36f":"#d9c8ff";X.lineWidth=2;X.setLineDash([5,5]);X.beginPath();X.arc(e.x,e.y,e.r+10,0,Math.PI*2);X.stroke();X.setLineDash([]);X.globalAlpha=.16;X.beginPath();X.moveTo(P.x,P.y);X.lineTo(e.x,e.y);X.stroke();X.globalAlpha=1}if(e.type==="charger"&&e.state==="aim"){let dx=P.x-e.x,dy=P.y-e.y,l=hyp(dx,dy)||1;X.strokeStyle="#ffd36f55";X.lineWidth=2;X.setLineDash([8,8]);X.beginPath();X.moveTo(e.x,e.y);X.lineTo(e.x+dx/l*190,e.y+dy/l*190);X.stroke();X.setLineDash([])}X.fillStyle=(e.flash||0)>0?"#ffffff":COLORS[e.type];X.beginPath();if(e.type==="boss"){const p=bossData(e.bossStage),pulse=2+Math.sin(S.t*4)*3;X.fillStyle=(e.flash||0)>0?"#ffffff":p.color;X.beginPath();X.arc(e.x,e.y,e.r+pulse,0,Math.PI*2);X.fill();X.strokeStyle="#ffffff88";X.lineWidth=3;X.beginPath();X.arc(e.x,e.y,e.r+10+Math.sin(S.t*2)*3,0,Math.PI*2);X.stroke();X.fillStyle="#2b1328";X.beginPath();X.arc(e.x-8,e.y-4,3,0,Math.PI*2);X.arc(e.x+8,e.y-4,3,0,Math.PI*2);X.fill();X.strokeStyle="#2b1328";X.lineWidth=2;X.beginPath();X.arc(e.x,e.y+5,8,.15,Math.PI-.15);X.stroke()}else if(e.type==="core"){let er=e.r+Math.sin(S.t*5+e.pulse)*2;X.arc(e.x,e.y,er,0,Math.PI*2);X.fill();X.strokeStyle="#e7d7ff";X.lineWidth=2;X.beginPath();X.arc(e.x,e.y,er+7,0,Math.PI*2);X.stroke()}else if(e.type==="charger"){X.save();X.translate(e.x,e.y);X.rotate(Math.PI/4);X.fillRect(-10,-10,20,20);X.restore()}else{X.arc(e.x,e.y,e.r,0,Math.PI*2);X.fill()}X.fillStyle="#241b2b";X.globalAlpha=.78;if(e.type==="chaser"){X.beginPath();X.arc(e.x-4,e.y-2,1.5,0,Math.PI*2);X.arc(e.x+4,e.y-2,1.5,0,Math.PI*2);X.fill();X.strokeStyle="#241b2b";X.lineWidth=1.3;X.beginPath();X.arc(e.x,e.y+3,3.5,.2,Math.PI-.2);X.stroke()}else if(e.type==="charger"){X.fillRect(e.x-5,e.y-3,2.5,3);X.fillRect(e.x+2.5,e.y-3,2.5,3)}else if(e.type!=="boss"){X.beginPath();X.arc(e.x-4,e.y-2,1.3,0,Math.PI*2);X.arc(e.x+4,e.y-2,1.3,0,Math.PI*2);X.fill();X.fillStyle="#ffb7d0";X.beginPath();X.arc(e.x-7,e.y+3,2,0,Math.PI*2);X.arc(e.x+7,e.y+3,2,0,Math.PI*2);X.fill()}X.globalAlpha=1}
 X.globalAlpha=S.invuln>0?(.45+.45*Math.sin(S.t*25)):1;X.fillStyle=S.over>0?COLORS.gold:COLORS.player;X.beginPath();X.arc(P.x,P.y,P.r+(S.dashTime>0?3:0),0,Math.PI*2);X.fill();X.strokeStyle="#fff";X.lineWidth=2;X.beginPath();X.moveTo(P.x,P.y);X.lineTo(P.x+P.faceX*18,P.y+P.faceY*18);X.stroke();X.globalAlpha=1;
 if(!pipWithPlayer()){X.save();X.globalAlpha=.22;X.strokeStyle="#ffb7c9";X.lineWidth=1.5;X.setLineDash([4,6]);X.beginPath();X.moveTo(P.x,P.y);X.lineTo(P.pipX,P.pipY);X.stroke();X.setLineDash([]);X.restore()}
 const px=P.pipX,py=P.pipY;if(pipWithPlayer()&&(S.pipRelayBuff>0||S.supportRush>0)){X.strokeStyle=S.pipRelayBuff>0?"#ffd36f88":"#d9c8ff88";X.lineWidth=1.5;X.beginPath();X.arc(px,py,13+Math.sin(S.t*9)*2,0,Math.PI*2);X.stroke()}X.save();X.translate(px,py);X.rotate(P.pipAngle*.35);X.fillStyle=!pipWithPlayer()?"#ffb7c9":S.over>0?"#fff0a8":"#ffd36f";X.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2===0?((S.over>0?9:7)+Math.min(3,(S.pipLevel-1)*.4)):3.2,xx=Math.cos(a)*r,yy=Math.sin(a)*r;i?X.lineTo(xx,yy):X.moveTo(xx,yy)}X.closePath();X.fill();X.rotate(-P.pipAngle*.35);X.fillStyle="#47340d";X.beginPath();X.arc(-2,-1,1,0,Math.PI*2);X.arc(2,-1,1,0,Math.PI*2);X.fill();if(S.pipHappy>0){X.strokeStyle="#47340d";X.lineWidth=1;X.beginPath();X.arc(0,1,2.4,0,Math.PI);X.stroke()}X.restore();if(S.pipLevel>=4){const hx=px+Math.cos(-P.pipAngle*1.7)*13,hy=py+Math.sin(-P.pipAngle*1.7)*13;X.fillStyle="#ff9fba";X.font="12px system-ui";X.textAlign="center";X.fillText("♥",hx,hy+4);X.textAlign="start"}
 for(const t of texts){if(!worldVisible(t.x,t.y,220))continue;X.globalAlpha=t.a;X.fillStyle=t.c;X.font=`${t.big?22:13}px system-ui`;X.textAlign="center";if(t.pipText){const maxWidth=Math.min(420,W*.58),lines=wrapCanvasText(X,t.t,maxWidth),lineHeight=t.big?25:17,startY=t.y-(lines.length-1)*lineHeight;for(let i=0;i<lines.length;i++)X.fillText(lines[i],t.x,startY+i*lineHeight)}else X.fillText(t.t,t.x,t.y)}X.globalAlpha=1;X.textAlign="start";X.restore();
 if(S.bossActive){const b=enemies.find(e=>e.type==="boss"&&!e.dead),p=bossData();if(b){const bw=Math.min(420,W*.72),bx=(W-bw)/2,by=76;X.fillStyle="#120912cc";X.fillRect(bx,by,bw,12);X.fillStyle=p.color;X.fillRect(bx,by,bw*clamp(b.hp/b.maxHp,0,1),12);X.strokeStyle="#ffffff66";X.strokeRect(bx,by,bw,12);X.fillStyle="#fff";X.font="bold 11px system-ui";X.textAlign="center";X.fillText(p.name,W/2,by-7);X.textAlign="start"}}
 for(let i=0;i<S.maxShields;i++){X.fillStyle=i<S.shields?"#7ed8ff":"#243340";X.fillRect(14+i*13,H-19,8,8)}if(flash>0){X.globalAlpha=flash*.45;X.fillStyle=S.health>0?"#ffffff":"#ff6e8b";X.fillRect(-30,-30,W+60,H+60);X.globalAlpha=1}X.restore();
}
