qaButtonB59('Autonomous behavior checks',()=>{qaFrozenB59=false;$('qaResults').textContent=runAutonomyChecks().map(r=>`${r.ok?'PASS':'FAIL'} ${r.name}${r.error?': '+r.error:''}`).join('\n');qaFrozenB59=true});
function reunionSceneB83(trusted){transportFixtureB60();S.shields=3;P.pipX=P.x=0;P.pipY=P.y=0;S.pipLove=3;feelingsB76().trust=trusted?.8:.5;enemies=[{type:'chaser',x:0,y:90,r:12,hp:20,dead:false,age:0,speed:0},{type:'charger',x:110,y:0,r:14,hp:20,dead:false,age:0,state:'charge',vx:-340,vy:0,charge:.52}];shots=[];reunitePipB60();for(const s of shots){s.x+=s.vx*.1;s.y+=s.vy*.1}qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`${trusted?'Trusted':'Fresh'} Pip: three reunion shots ${shots[1].vx>530?'toward charging threat':'toward nearest enemy'}`}
qaButtonB59('B83 fresh reunion',()=>reunionSceneB83(false));
qaButtonB59('B83 trusted reunion',()=>reunionSceneB83(true));
qaButtonB59('B77 committed prediction',()=>{transportFixtureB60();S.shields=3;const e={type:'charger',x:130,y:0,r:14,hp:4,speed:0,dead:false,age:0,state:'aim',aim:1,vx:0,vy:0};enemies=[e];for(let i=0;i<21;i++){P.y+=2;updateEnemy(e,.04)}qaFrozenB59=true;qaStatusB59()});
function patchSceneB78(remember){transportFixtureB60();P.pipX=0;S.shields=3;S.pipDetectRange=200;heartBits=[makeHeartSourceB74(3,100,0,40),makeHeartSourceB74(3,-125,0,40)];if(remember)rememberPatchB78(100,0);S.pipTarget=nextHeartSourceB74();qaFrozenB59=true;qaUpdateB59(.04);qaStatusB59();$('qaResults').textContent=`Chosen patch: ${S.pipTarget?.x}. Remembered patches: ${roughPatchesB78().length}`}
qaButtonB59('B78 fresh patch',()=>patchSceneB78(false));
qaButtonB59('B78 remembered patch',()=>patchSceneB78(true));
qaButtonB59('B79 missed charge',()=>{transportFixtureB60();S.shields=3;const e={type:'charger',x:100,y:0,r:14,hp:4,speed:0,dead:false,age:0,state:'charge',charge:.01,aim:1,vx:340,vy:0};enemies=[e];updateEnemy(e,.04);qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`Reset: ${e.b79.recover.toFixed(2)}s. Aim: ${e.aim.toFixed(2)}s`});
qaButtonB59('B80 danger replan',()=>{transportFixtureB60();P.pipX=0;P.pipY=0;S.shields=3;S.pipDetectRange=240;const threatened=makeHeartSourceB74(1,100,0),safe=makeHeartSourceB74(1,-100,0);heartBits=[threatened,safe];enemies=[{type:'drifter',x:100,y:0,r:12,hp:2,dead:false,age:0,vx:0,vy:0}];S.pipState='collect';S.pipTarget=threatened;updatePipTransportB60(.04);qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`Target: ${Math.round(S.pipTarget.x)}. Replans: ${replanStateB80().count}. Cue: ${replanStateB80().cue.toFixed(2)}s`});
qaButtonB59('B82 enemy rotations',()=>{const checks=runSurvivalChecksB63().filter(r=>r.name.startsWith('B82'));transportFixtureB60();S.stage=7;const rows=checks.map(r=>`${r.ok?'PASS':'FAIL'} ${r.name}${r.error?': '+r.error:''}`);for(let wave=1;wave<=3;wave++){S.stageWaveCount=wave;const roster=enemyRosterB82(),counts={chaser:0,core:0,charger:0};for(let i=0;i<1000;i++)counts[rosterEnemyB82(roster,i/1000)]++;rows.push(`${wave} ${roster.name} · cap ${enemyCap()} · ${counts.chaser}/${counts.core}/${counts.charger}`)}qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=rows.join('\n')});
function escalationSceneB84(hold){transportFixtureB60();S.shields=3;S.bossActive=true;S.bossCount=0;S.bossMidPraise=false;S.waveState='boss';const e={type:'boss',bossKey:1,x:P.x+180,y:P.y,r:30,hp:51,maxHp:100,dead:false,age:0,flash:0};enemies=[e];updateEnemy(e,.04);hitEnemy(e,3);const atThreshold=S.bossMidPraise;let frames=0;if(!hold){while(frames<400&&!S.bossMidPraise){updateEnemy(e,.04);frames++}}qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`HP ${e.hp}/${e.maxHp} · phase two ${e.b59.second} · cue at threshold ${atThreshold} · cue now ${S.bossMidPraise}${hold?'':` after ${frames} frames`}`}
qaButtonB59('B84 cue at threshold',()=>escalationSceneB84(true));
qaButtonB59('B84 cue at escalation',()=>escalationSceneB84(false));
function coverSceneB85(shotFirst){transportFixtureB60();P.x=P.y=P.vx=P.vy=0;P.pipX=8;P.pipY=0;S.pipState='orbit';S.shields=1;S.invuln=0;S.pipCompassion=2;S.waveState='active';partnershipB59().coverCd=0;enemyShots=[{x:60,y:0,vx:-600,vy:0,r:5,life:3}];enemies=shotFirst?[]:[{type:'chaser',x:0,y:40,r:12,dead:false,vx:0,vy:-60,hp:3,age:0}];const t=incomingThreatB59();partnershipB59().coverThreat=t;qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`Threat ${t?`${Math.round(t.x)},${Math.round(t.y)}`:'none'} · ${t&&t.x===60?'imminent shot':'body'} · bodies ${enemies.length}`}
qaButtonB59('B85 shot only',()=>coverSceneB85(true));
qaButtonB59('B85 shot vs later body',()=>coverSceneB85(false));
qaButtonB59('B86 display ratio',()=>{qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`dpr ${window.devicePixelRatio} · DPR ${DPR} · backing ${C.width}x${C.height} · css ${W}x${H} · ratio ${(C.width/W).toFixed(3)} · query ${b86Query?b86Query.media:'none'}`});
qaButtonB59('B87 focus release',()=>{transportFixtureB60();S.shields=3;S.overType='beam';S.heat=62;S.over=1;S.b38OverHeld=true;keys.add('d');Object.assign(joy,{active:true,id:87,dx:1,dy:0});Object.assign(tapDash,{time:99,x:20,y:30,type:'touch',sourcePointer:87});window.dispatchEvent(new Event('blur'));qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`keys ${keys.size} · joystick ${joy.active?'held':'released'} · Overdrive ${S.over>0?'held':'banked'} · HEAT ${S.heat} · tap ${tapDash.time?'armed':'cleared'}`});
qaButtonB59('B88 perimeter pressure',()=>{transportFixtureB60();S.shields=3;const counts={top:0,right:0,bottom:0,left:0};for(let i=0;i<1200;i++)counts[perimeterSpawnPointB88((i+.5)/1200,W,H,CAM.x,CAM.y,52).edge]++;enemies=['top','right','bottom','left'].map((edge,i)=>{const p=perimeterSpawnPointB88((i+.125)/4,W,H,CAM.x,CAM.y,52);return {type:['chaser','core','charger','chaser'][i],x:p.x,y:p.y,r:12,hp:3,dead:false,age:0,speed:0,state:'aim',aim:1,pulse:0,b88Edge:p.edge}});qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`B88 counts top/right/bottom/left ${counts.top}/${counts.right}/${counts.bottom}/${counts.left} at ${W}x${H}`});
qaButtonB59('B89 arrival read',()=>{transportFixtureB60();S.shields=3;enemies=[{type:'chaser',x:CAM.x,y:CAM.y-H/2-52,r:12,hp:2,dead:false,age:.1,speed:0},{type:'core',x:CAM.x+W/2+52,y:CAM.y,r:15,hp:1,dead:false,age:.1,speed:0,pulse:0},{type:'charger',x:CAM.x,y:CAM.y+H/2+52,r:14,hp:3,dead:false,age:.1,state:'aim',aim:1,speed:0},{type:'chaser',x:CAM.x-W/2-52,y:CAM.y,r:12,hp:2,dead:false,age:.1,speed:0}];const cues=enemies.map(e=>arrivalCueB89(e)?.edge).join('/');qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`B89 arrival cues ${cues} · enemies ${enemies.length} · ages ${enemies.map(e=>e.age.toFixed(1)).join('/')}`});
qaButtonB59('B90 dash ready',()=>{transportFixtureB60();S.shields=3;S.waveGoal=999;S.spawn=999;S.dashCd=.01;update(.02);const q=dashReadyCueB90();qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`B90 dash cue ${q?'ready':'missing'} · cd ${S.dashCd.toFixed(2)} · cue ${(S.b90DashReady||0).toFixed(2)}s · r ${q?q.r.toFixed(1):'n/a'}`});
qaButtonB59('B91 wave closeout',()=>{transportFixtureB60();S.shields=3;S.waveGoal=3;S.waveKills=0;S.spawn=999;enemies=[{type:'chaser',x:P.x+50,y:P.y,r:12,hp:1,dead:false,age:0,speed:0}];kill(enemies[0]);const q=waveCloseCueB91();qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`B91 wave closeout ${q?q.text:'missing'} · kills ${S.waveKills}/${S.waveGoal} · cue ${(S.b91WaveCloseCue||0).toFixed(2)}s`});
qaButtonB59('B92 charge gates',()=>{transportFixtureB60();S.shields=3;S.overType='beam';S.heat=24.99;const low=canIgniteOverdriveB38('beam');S.heat=25;const beam=canIgniteOverdriveB38('beam');S.overType='pip';S.heat=69.99;const pipLow=canIgniteOverdriveB38('pip');S.heat=70;const pipFull=canIgniteOverdriveB38('pip');qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`Beam 24.99 ${low?'open':'locked'} · Beam 25 ${beam?'open':'locked'} · Pip 69.99 ${pipLow?'open':'locked'} · Pip 70 ${pipFull?'open':'locked'}`});
qaButtonB59('B93 charged storm',()=>{transportFixtureB60();S.shields=3;S.overType='storm';S.overUnlocked.add('storm');S.overLevels.storm=2;S.pipBossPowers.constellation=2;S.heat=70;enemies=[0,1,2,3,4].map(i=>({type:'chaser',x:P.x+45+i*28,y:P.y+(i%2?24:-18),r:12,hp:20,maxHp:20,dead:false,age:1,speed:0}));triggerOverdrive();tickStormB93(1.1);const gathered=S.b93StormCharge.clouds,heat=S.heat;stopOverdriveB38(false);const cooldown=S.b93StormCooldown;for(let i=0;i<50;i++)tickStormB93(.04);qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`B93 gathered ${gathered}/5 · HEAT ${heat.toFixed(0)} · clouds left ${S.b93StormClouds.length} · enemies struck ${enemies.filter(e=>e.hp<20).length}/5 · cooldown began ${cooldown.toFixed(2)}s`});
qaButtonB59('B93 gathering clouds',()=>{transportFixtureB60();S.shields=3;S.overType='storm';S.overUnlocked.add('storm');S.overLevels.storm=2;S.heat=70;enemies=[0,1,2].map(i=>({type:'chaser',x:P.x+70+i*38,y:P.y,r:12,hp:20,maxHp:20,dead:false,age:1,speed:0}));triggerOverdrive();tickStormB93(.82);qaFrozenB59=true;qaStatusB59();$('qaResults').textContent=`B93 holding · ${S.b93StormCharge.clouds}/5 clouds · HEAT ${S.heat.toFixed(0)} · damage ${enemies.filter(e=>e.hp<20).length}`});
